import Head from 'next/head'
import Image from 'next/image'
import ToDo from '../Components/ToDo'
 

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-Orange-custom-light'>
        <ToDo />
      </main>
    </div>
  )
}
